# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8636c1b8c42f7ec402e25cdb472991696ca6e23edb5af51c5a9e75866d7660ca0a1d3e3bc042f932d8358c1a2939a4f4f32cc9b3f17637a88a70424c873392f0

test:
  secret_key_base: 240b85889dfff923974de962398fc19b30151941387edb56eaa692c6471c2e9306d772016b079dc6491c53dad7d11709e92f820bb934ea522544a0f82cc8c8da

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
